[[main]]
name = "Accueil"
url = "fr/"
weight = 10
[[main]]
name = "À propos de moi"
pre = "fr/#"
url = "about"
weight = 20
[[main]]
name = "Services"
pre = "fr/#"
url = "service"
weight = 30
[[main]]
name = "Portfolio"
pre = "fr/#"
url = "portfolio"
weight = 40
[[main]]
name = "Témoignages"
pre = "fr/#"
url = "testimonial"
weight = 50
[[main]]
name = "Blog"
url = "blog"
weight = 55
[[main]]
name = "Me contacter"
pre = "fr/#"
url = "contact"
weight = 60